### ISSUE TITLE
views in the resource folder not necessary?

### ISSUE THREAD

**Issue by torian257x** [LaravelDaily/Laravel-Vue-First-CRUD#2]
you didnt really mention the views

why is there `<router-view` twice?

why the other 2 views?  e.g. edit and create https://github.com/LaravelDaily/Laravel-Vue-First-CRUD/blob/master/resources/views/admin/companies/edit.blade.php

**Comment by PovilasKorop** [comment]
@Jossnaz thanks for the issue.

Two views - One of them loads default page due to the fact that we are relaying on both - laravel and VueJS routers. The second one could be removed but then the default route loading should be transfered to app.js and would add complexity. (unless router changed and now accepts a default route parameter and then still continues to work with other routes.

Other two views - indeed they were unnecessary, removed them.
